### ISSUE TITLE
Unable to estimate target position

### ISSUE THREAD

**Issue by sauranildebs** [rishab26201/SDRE_Landing#1]
https://github.com/rishab26201/SDRE_Landing/blob/202462d7dc36cf8de4d128ca023b195319b03163/quadcopter/script/kalman_filter_cam.py#L270

What's the purpose of this?
And why use https://github.com/rishab26201/SDRE_Landing/blob/202462d7dc36cf8de4d128ca023b195319b03163/quadcopter/script/kalman_filter_cam.py#L257 ?
The two basically cancels out each other. Dont they?

**Comment by sauranildebs** [comment]
Any specific reason for hardcoding this value?
https://github.com/rishab26201/SDRE_Landing/blob/202462d7dc36cf8de4d128ca023b195319b03163/quadcopter/script/kalman_filter_cam.py#L139

**Comment by rishabbala** [comment]
`yaw = yaw-np.pi/2`
This is because the axis in mavros and gazebo are 90 degrees off from each other. This change is used only in the rotational matrices


` y = -info.pose.pose.position.x `
The positions published by mavros are in its coordinate frame. To convert to gazebo frame I have to change swap the data from x and y.

Assume that mavros has axes x and y as East, North and gazebo has the axes as North, West.

The two things dont cancel out as for eg. mavros gives yaw as 90 deg and posn (5,2) whereas the data in gazebo is supposed to be 0 deg and (2,-5).

`msg.goal.z = 0.43582 `
I assume that the rover moves in a flat plane, and hence that the height on which I have to land is constant. This value is the height of the rover.

All the data and calculations in the kalman_filter code are in the global frame. They are converted to the local frame in the control code.
